// SPDX-License-Identifier: BSD-3-Clause
// MAME-derived portions copyright-holder: David Haywood
// XaviXEmu port and modifications:
// Copyright (c) 2026 Billy Jr. and contributors
/*
 * Small, deterministic XaviX/SSD 2000 video renderer.
 *
 * The rendering behaviour is derived from MAME's BSD-3-Clause XaviX video
 * implementation by David Haywood (src/mame/tvgames/xavix_v.cpp).  This file
 * is an independent C port and has no dependency on the MAME runtime.
 */

#ifndef DRGQST_XAVIX_VIDEO_H
#define DRGQST_XAVIX_VIDEO_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum
{
	XAVIX_VIDEO_WIDTH = 256,
	XAVIX_VIDEO_HEIGHT = 224,
	XAVIX_VIDEO_VISIBLE_Y_START = 16,
	XAVIX_VIDEO_VISIBLE_Y_END = 239,
	XAVIX_VIDEO_PIXELS = XAVIX_VIDEO_WIDTH * XAVIX_VIDEO_HEIGHT,
	XAVIX_VIDEO_PALETTE_ENTRIES = 512,
	XAVIX_VIDEO_FRAGMENT_BYTES = 0x800,
	XAVIX_VIDEO_SEGMENT_BYTES = 0x20,
	XAVIX_VIDEO_TILEMAP_REGISTER_BYTES = 8
};

/* colmix_control bits used by the game when all three drawing sources are on. */
enum
{
	XAVIX_VIDEO_COLMIX_TILEMAP_0 = 0x01,
	XAVIX_VIDEO_COLMIX_TILEMAP_1 = 0x02,
	XAVIX_VIDEO_COLMIX_SPRITES = 0x04
};

enum
{
	/* Apply the low three colmix_control enable bits.  Leave this flag clear
	 * for exact parity with the current MAME renderer, which stores but does
	 * not yet apply those incompletely understood registers. */
	XAVIX_VIDEO_INPUT_COLMIX_ENABLES_VALID = 0x01
};

typedef uint8_t (*xavix_video_read8_fn)(void *opaque, uint32_t address);

typedef struct xavix_video_bounds
{
	int16_t min_x;
	int16_t min_y;
	int16_t max_x;
	int16_t max_y;
	uint8_t valid;
} xavix_video_bounds;

typedef struct xavix_video_sprite_watch
{
	uint32_t first_address;
	uint32_t last_address;
	uint16_t address_stride;
	uint8_t required_sprite_mode;
	uint8_t enabled;
} xavix_video_sprite_watch;

/*
 * The machine owns all memory supplied here.  The pointed-to data only needs
 * to remain valid for the duration of xavix_video_render().
 *
 * read_program_byte receives the 24-bit address generated by the video unit.
 * Direct low-bus arrays below take precedence, allowing the common RAM and
 * register paths to avoid a callback.  A missing callback reads as zero.
 */
typedef struct xavix_video_inputs
{
	const uint8_t *main_ram;
	size_t main_ram_size;
	const uint8_t *fragment_ram;       /* at least 0x800 bytes, or NULL */
	const uint8_t *palette_sh;         /* packed Y/C/H low byte */
	const uint8_t *palette_l;          /* packed Y/C/H high byte */
	uint16_t palette_entries;          /* zero means 256, maximum 512 */
	const uint8_t *segment_regs;       /* at least 0x20 bytes, or NULL */
	const uint8_t *tilemap_regs[2];    /* each points to eight bytes */

	uint8_t sprite_mode;
	uint8_t arena_start;
	uint8_t arena_end;
	uint8_t arena_control;
	uint8_t colmix_sh;
	uint8_t colmix_l;
	uint8_t colmix_control;
	uint8_t flags;

	xavix_video_read8_fn read_program_byte;
	void *read_program_opaque;
} xavix_video_inputs;

typedef struct xavix_video_frame_report
{
	/* Native XaviX coordinates: x=0..255, y=16..239. */
	xavix_video_bounds hardware_clip;
	/* Cropped framebuffer coordinates: x=0..255, y=0..223. */
	xavix_video_bounds watched_sprite_bounds;
	uint32_t watched_sprite_pixels;
	uint32_t memory_reads;
	uint32_t opaque_pixels_drawn;
	uint16_t tile_entries_visited[2];
	uint16_t sprites_visited;
	uint16_t malformed_inline_headers;
	uint32_t colmix_argb;
	uint8_t sprite_mode_supported;
	uint8_t watched_sprite_visible;
} xavix_video_frame_report;

/* Public so the standalone machine can allocate it without a heap.  The
 * framebuffer is top-to-bottom 0xffRRGGBB with a 256-pixel stride.  Native
 * scanlines 16..239 are cropped to framebuffer rows 0..223. */
typedef struct xavix_video
{
	uint32_t framebuffer[XAVIX_VIDEO_PIXELS];
	uint8_t zbuffer[XAVIX_VIDEO_PIXELS];
	uint8_t pixel_owner[XAVIX_VIDEO_PIXELS];
	uint32_t palette_argb[XAVIX_VIDEO_PALETTE_ENTRIES];
	uint8_t palette_opaque[XAVIX_VIDEO_PALETTE_ENTRIES];
	xavix_video_sprite_watch sprite_watch;
	xavix_video_frame_report report;
} xavix_video;

void xavix_video_init(xavix_video *video);
void xavix_video_reset(xavix_video *video);

/* Restores the built-in Dragon Quest feather/pen detector. */
void xavix_video_watch_drgqst_feather(xavix_video *video);
void xavix_video_set_sprite_watch(xavix_video *video, const xavix_video_sprite_watch *watch);

const xavix_video_frame_report *xavix_video_render(
	xavix_video *video,
	const xavix_video_inputs *inputs);

const uint32_t *xavix_video_framebuffer(const xavix_video *video);
const xavix_video_frame_report *xavix_video_last_report(const xavix_video *video);
int xavix_video_feather_visible(const xavix_video *video);
int xavix_video_feather_bounds(const xavix_video *video, xavix_video_bounds *bounds);

/* Helpers for the machine's memory-mapped write path. */
void xavix_video_fragment_write(uint8_t fragment_ram[XAVIX_VIDEO_FRAGMENT_BYTES],
	uint16_t offset, uint8_t data);
uint32_t xavix_video_palette_decode(uint8_t sh, uint8_t l, int *opaque);

#ifdef __cplusplus
}
#endif

#endif
