// SPDX-License-Identifier: BSD-3-Clause
// MAME-derived portions copyright-holders: ramacat, David Haywood
// XaviXEmu port and modifications:
// Copyright (c) 2026 Billy Jr. and contributors
/*
 * Deterministic, pointer-free XaviX/SSD 2000 audio state.
 *
 * Behaviour is derived from the BSD-3-Clause MAME xavix_sound.cpp and the
 * sound register handlers in xavix_m.cpp.  No MAME runtime types are used.
 */

#ifndef DRGQST_XAVIX_AUDIO_H
#define DRGQST_XAVIX_AUDIO_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum
{
	XAVIX_AUDIO_VOICES = 16,
	XAVIX_AUDIO_TEMPO_GROUPS = 4,
	XAVIX_AUDIO_DEFAULT_MASTER_CLOCK = 21477272,
	XAVIX_AUDIO_DEFAULT_HOST_RATE = 48000,
	XAVIX_AUDIO_MMIO_BASE = 0x75f0,
	XAVIX_AUDIO_MMIO_BYTES = 16
};

enum xavix_audio_mmio_offset
{
	XAVIX_AUDIO_VOICE_START_LO = 0x00,
	XAVIX_AUDIO_VOICE_START_HI = 0x01,
	XAVIX_AUDIO_VOICE_UPDATE_LO = 0x02,
	XAVIX_AUDIO_VOICE_UPDATE_HI = 0x03,
	XAVIX_AUDIO_VOICE_STATUS_LO = 0x04,
	XAVIX_AUDIO_VOICE_STATUS_HI = 0x05,
	XAVIX_AUDIO_MASTER_VOLUME = 0x06,
	XAVIX_AUDIO_REGISTER_PAGE = 0x07,
	XAVIX_AUDIO_CYCLE_RATE = 0x08,
	XAVIX_AUDIO_MIXER = 0x09,
	XAVIX_AUDIO_TEMPO_0 = 0x0a,
	XAVIX_AUDIO_TEMPO_1 = 0x0b,
	XAVIX_AUDIO_TEMPO_2 = 0x0c,
	XAVIX_AUDIO_TEMPO_3 = 0x0d,
	XAVIX_AUDIO_IRQ_STATUS = 0x0e,
	XAVIX_AUDIO_DAC_CONTROL = 0x0f
};

typedef uint8_t (*xavix_audio_read_register_byte_fn)(void *context, uint16_t address);
typedef void (*xavix_audio_write_register_byte_fn)(void *context, uint16_t address, uint8_t data);
typedef uint8_t (*xavix_audio_read_program_byte_fn)(void *context, uint32_t address);

/* Register callbacks receive absolute low-bus RAM addresses.  Program reads
 * receive the 24-bit sample/envelope address generated by the sound unit. */
typedef struct xavix_audio_bus
{
	xavix_audio_read_register_byte_fn read_register_byte;
	xavix_audio_write_register_byte_fn write_register_byte;
	xavix_audio_read_program_byte_fn read_program_byte;
	void *context;
} xavix_audio_bus;

typedef struct xavix_audio_voice
{
	uint32_t position;
	uint32_t loop_position;
	uint32_t start_position;
	uint32_t rate;
	uint32_t env_pos_left;
	uint32_t env_pos_right;
	uint32_t env_period_ticks;
	uint32_t env_countdown;
	uint16_t env_rom_base_left;
	uint16_t env_rom_base_right;
	uint16_t noise_state;
	uint8_t enabled;
	uint8_t bank;
	uint8_t type;
	uint8_t volume;
	uint8_t env_bank;
	uint8_t env_mode;
	uint8_t env_volume_left;
	uint8_t env_volume_right;
	uint8_t env_active_left;
	uint8_t env_active_right;
} xavix_audio_voice;

/* Contains no pointers and may be copied as part of an in-process save state.
 * External main RAM addressed by the bus must be saved by the machine too. */
typedef struct xavix_audio
{
	xavix_audio_voice voice[XAVIX_AUDIO_VOICES];
	/* Host-rate conversion state.  resample_phase is the remaining duration
	 * of the currently latched native sample, measured in host-rate ticks. */
	uint64_t resample_phase;
	uint64_t native_ticks_generated;
	uint64_t host_frames_generated;
	uint32_t master_clock_hz;
	uint32_t native_rate_hz;
	uint32_t host_rate_hz;
	uint32_t tempo_irq_period[XAVIX_AUDIO_TEMPO_GROUPS];
	uint32_t tempo_irq_countdown[XAVIX_AUDIO_TEMPO_GROUPS];
	int16_t last_native_left;
	int16_t last_native_right;
	int16_t mixer_gain;
	uint8_t default_tempo;
	uint8_t tempo_register[XAVIX_AUDIO_TEMPO_GROUPS];
	uint8_t tempo_divider[XAVIX_AUDIO_TEMPO_GROUPS];
	uint8_t cycle_rate_register;
	uint8_t cycle_rate_divider;
	uint8_t voice_start[2];
	uint8_t register_page;
	uint8_t irq_status;
	uint8_t master_volume;
	uint8_t mixer_monaural;
	uint8_t mixer_capacity;
	uint8_t mixer_amp;
	uint8_t dac_broadcast;
	uint8_t dac_gap;
	uint8_t dac_lead;
	uint8_t dac_lag;
} xavix_audio;

void xavix_audio_init(xavix_audio *audio, uint32_t master_clock_hz,
	uint32_t host_rate_hz, uint8_t default_tempo);
void xavix_audio_reset(xavix_audio *audio);

/* offset is 0x00..0x0f for CPU addresses 0x75f0..0x75ff.  The machine should
 * generate/advance audio to the current emulated time before a write. */
uint8_t xavix_audio_read(xavix_audio *audio, const xavix_audio_bus *bus,
	unsigned offset);
void xavix_audio_write(xavix_audio *audio, const xavix_audio_bus *bus,
	unsigned offset, uint8_t data);

/* Produces interleaved signed 16-bit stereo at host_rate_hz.  Passing NULL for
 * output advances deterministically without storing samples. */
size_t xavix_audio_generate(xavix_audio *audio, const xavix_audio_bus *bus,
	int16_t *interleaved_stereo, size_t frames);

uint16_t xavix_audio_active_voices(const xavix_audio *audio);
int xavix_audio_irq_pending(const xavix_audio *audio);
uint32_t xavix_audio_native_rate(const xavix_audio *audio);

#ifdef __cplusplus
}
#endif

#endif
