#ifndef XAVIX_GAME_CONTROLS_H
#define XAVIX_GAME_CONTROLS_H

#include <stddef.h>
#include <stdint.h>

#include "controller_input.h"
#include "rom_loader.h"

enum xavix_game_control_label
{
	XAVIX_GAME_CONTROL_NONE = 0,
	XAVIX_GAME_CONTROL_ATTACK,
	XAVIX_GAME_CONTROL_SECOND_ATTACK,
	XAVIX_GAME_CONTROL_DEFENSE,
	XAVIX_GAME_CONTROL_SPECIAL,
	XAVIX_GAME_CONTROL_MAGIC,
	XAVIX_GAME_CONTROL_CONFIRM,
	XAVIX_GAME_CONTROL_BACK,
	XAVIX_GAME_CONTROL_LEFT_SENSOR,
	XAVIX_GAME_CONTROL_RIGHT_SENSOR,
	XAVIX_GAME_CONTROL_BOTH_SENSORS,
	XAVIX_GAME_CONTROL_DEFLECT,
	XAVIX_GAME_CONTROL_ACCELERATE,
	XAVIX_GAME_CONTROL_BRAKE,
	XAVIX_GAME_CONTROL_PAUSE,
	XAVIX_GAME_CONTROL_REAR_COMMAND,
	XAVIX_GAME_CONTROL_HORN_SELECT,
	XAVIX_GAME_CONTROL_NITRO,
	XAVIX_GAME_CONTROL_REVERSE,
	XAVIX_GAME_CONTROL_IGNITION_KEY,
	XAVIX_GAME_CONTROL_SIREN_TRANSFORM,
	XAVIX_GAME_CONTROL_LIGHTS,
	XAVIX_GAME_CONTROL_WIPERS,
	XAVIX_GAME_CONTROL_FORWARD_GO,
	XAVIX_GAME_CONTROL_SELECT,
	XAVIX_GAME_CONTROL_MAP,
	XAVIX_GAME_CONTROL_MICROPHONE,
	XAVIX_GAME_CONTROL_PLAYER1_ACTION,
	XAVIX_GAME_CONTROL_PLAYER2_ACTION,
	XAVIX_GAME_CONTROL_LEFT_PAD,
	XAVIX_GAME_CONTROL_RIGHT_PAD,
	XAVIX_GAME_CONTROL_LEFT_PUNCH,
	XAVIX_GAME_CONTROL_RIGHT_PUNCH,
	XAVIX_GAME_CONTROL_CARD_ACTION,
	XAVIX_GAME_CONTROL_BAZOOKA,
	XAVIX_GAME_CONTROL_REVERSE_SENSOR,
	XAVIX_GAME_CONTROL_SPIN_SENSOR,
	XAVIX_GAME_CONTROL_SWORD_ATTACK,
	XAVIX_GAME_CONTROL_SABER_SPIN,
	XAVIX_GAME_CONTROL_RED_BUTTON,
	XAVIX_GAME_CONTROL_BLUE_SWORD,
	XAVIX_GAME_CONTROL_RED_SWORD,
	XAVIX_GAME_CONTROL_BLUE_TRIGGER,
	XAVIX_GAME_CONTROL_RED_TRIGGER,
	XAVIX_GAME_CONTROL_CADDY_CONFIRM,
	XAVIX_GAME_CONTROL_MODEL_BACK,
	XAVIX_GAME_CONTROL_JOIN_HANDS,
	XAVIX_GAME_CONTROL_EXECUTE,
	XAVIX_GAME_CONTROL_FIRST_REFLECTOR_ATTACK,
	XAVIX_GAME_CONTROL_SECOND_REFLECTOR_ATTACK,
	XAVIX_GAME_CONTROL_TWO_HAND_ATTACK,
	XAVIX_GAME_CONTROL_TILT_FORWARD,
	XAVIX_GAME_CONTROL_TILT_BACKWARD,
	XAVIX_GAME_CONTROL_TILT_LEFT,
	XAVIX_GAME_CONTROL_TILT_RIGHT,
	XAVIX_GAME_CONTROL_TILT_CENTER,
	XAVIX_GAME_CONTROL_TAKECOPTER_BOOST,
	XAVIX_GAME_CONTROL_COUNT
};

enum xavix_game_control_feature
{
	XAVIX_GAME_CONTROL_FEATURE_POINTER = UINT32_C(1) << 0,
	XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING = UINT32_C(1) << 1,
	XAVIX_GAME_CONTROL_FEATURE_MOTION = UINT32_C(1) << 2,
	XAVIX_GAME_CONTROL_FEATURE_DUAL_MOTION = UINT32_C(1) << 3,
	XAVIX_GAME_CONTROL_FEATURE_KEYBOARD = UINT32_C(1) << 4,
	XAVIX_GAME_CONTROL_FEATURE_WII_REMOTE = UINT32_C(1) << 5
};

typedef struct xavix_game_control_profile
{
	enum drgqst_rom_kind kind;
	enum xavix_game_control_label actions[XAVIX_CONTROLLER_ACTION_COUNT];
	uint32_t features;
} xavix_game_control_profile;

const xavix_game_control_profile *xavix_game_control_profile_for_kind(
	enum drgqst_rom_kind kind);
int xavix_game_control_action_visible(const xavix_game_control_profile *profile,
	enum xavix_controller_action action);
size_t xavix_game_control_profile_count(void);
const xavix_game_control_profile *xavix_game_control_profile_at(size_t index);

uint32_t xavix_takecopter_ir_code(int forward, int backward,
	int left, int right);

const wchar_t *xavix_game_control_label_text(
	 enum xavix_game_control_label label, unsigned language);

#endif
