#include "game_controls.h"

#include <stddef.h>

#define PROFILE(game_kind, primary, secondary, defense, special, confirm, two_hand, deflect, game_features) \
	{ game_kind, { primary, secondary, defense, special, confirm, two_hand, deflect }, game_features }

uint32_t xavix_takecopter_ir_code(int forward, int backward,
	int left, int right)
{
	static const uint32_t serial_codes[16] =
	{
		UINT32_C(0x0199e667), UINT32_C(0x0199e001),
		UINT32_C(0x019987ff), UINT32_C(0x01999999),
		UINT32_C(0x01986679), UINT32_C(0x0198601f),
		UINT32_C(0x019807e1), UINT32_C(0x01981987),
		UINT32_C(0x0181e787), UINT32_C(0x0181e1e1),
		UINT32_C(0x0181861f), UINT32_C(0x01819879),
		UINT32_C(0x01866799), UINT32_C(0x018661ff),
		UINT32_C(0x01860601), UINT32_C(0x01861867)
	};
	unsigned longitudinal = 0;
	unsigned lateral = 0;

	/* ROM dynamics confirm that decoded bits $01/$04 are forward/backward
	 * acceleration, while $10/$40 are left/right steering. */
	if (forward && backward)
		longitudinal = 3;
	else if (backward)
		longitudinal = 1;
	else if (forward)
		longitudinal = 2;
	if (left && right)
		lateral = 3;
	else if (right)
		lateral = 1;
	else if (left)
		lateral = 2;
	return serial_codes[longitudinal * 4 + lateral];
}

static const xavix_game_control_profile GAME_CONTROL_PROFILES[] =
{
	PROFILE(DRGQST_ROM_DRAGON_QUEST,
		XAVIX_GAME_CONTROL_ATTACK, XAVIX_GAME_CONTROL_MAGIC,
		XAVIX_GAME_CONTROL_DEFENSE, XAVIX_GAME_CONTROL_SPECIAL,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_MOTION),
	PROFILE(DRGQST_ROM_BAN_ONEP,
		XAVIX_GAME_CONTROL_ATTACK, XAVIX_GAME_CONTROL_RIGHT_SENSOR,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_BAZOOKA,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_POINTER |
		XAVIX_GAME_CONTROL_FEATURE_DUAL_MOTION),
	PROFILE(DRGQST_ROM_BAN_OMT,
		XAVIX_GAME_CONTROL_ATTACK, XAVIX_GAME_CONTROL_SECOND_ATTACK,
		XAVIX_GAME_CONTROL_REVERSE_SENSOR, XAVIX_GAME_CONTROL_SPIN_SENSOR,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_MOTION),
	PROFILE(DRGQST_ROM_TTV_LOTR,
		XAVIX_GAME_CONTROL_SWORD_ATTACK, XAVIX_GAME_CONTROL_SECOND_ATTACK,
		XAVIX_GAME_CONTROL_DEFENSE, XAVIX_GAME_CONTROL_SPECIAL,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_MOTION),
	PROFILE(DRGQST_ROM_TTV_SW,
		XAVIX_GAME_CONTROL_SWORD_ATTACK, XAVIX_GAME_CONTROL_SECOND_ATTACK,
		XAVIX_GAME_CONTROL_DEFENSE, XAVIX_GAME_CONTROL_SABER_SPIN,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_MOTION),
	PROFILE(DRGQST_ROM_TTV_SWJ,
		XAVIX_GAME_CONTROL_SWORD_ATTACK, XAVIX_GAME_CONTROL_SECOND_ATTACK,
		XAVIX_GAME_CONTROL_DEFENSE, XAVIX_GAME_CONTROL_SABER_SPIN,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_MOTION),
	PROFILE(DRGQST_ROM_TTV_MX,
		XAVIX_GAME_CONTROL_ACCELERATE, XAVIX_GAME_CONTROL_BRAKE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_PAUSE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING),
	PROFILE(DRGQST_ROM_TOM_JUMP,
		XAVIX_GAME_CONTROL_ACCELERATE, XAVIX_GAME_CONTROL_BRAKE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_PAUSE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING),
	PROFILE(DRGQST_ROM_EPO_SDB,
		XAVIX_GAME_CONTROL_PLAYER1_ACTION, XAVIX_GAME_CONTROL_PLAYER2_ACTION,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_DUAL_MOTION),
	PROFILE(DRGQST_ROM_EPO_BOWL,
		XAVIX_GAME_CONTROL_CONFIRM, XAVIX_GAME_CONTROL_BACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_MOTION),
	PROFILE(DRGQST_ROM_BAN_NARU,
		XAVIX_GAME_CONTROL_EXECUTE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_JOIN_HANDS, XAVIX_GAME_CONTROL_SPECIAL,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_DUAL_MOTION |
		XAVIX_GAME_CONTROL_FEATURE_WII_REMOTE),
	PROFILE(DRGQST_ROM_BAN_BLDJ,
		XAVIX_GAME_CONTROL_FIRST_REFLECTOR_ATTACK,
		XAVIX_GAME_CONTROL_SECOND_REFLECTOR_ATTACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_TWO_HAND_ATTACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_DUAL_MOTION |
		XAVIX_GAME_CONTROL_FEATURE_WII_REMOTE),
	PROFILE(DRGQST_ROM_BAN_DB2J,
		XAVIX_GAME_CONTROL_ATTACK, XAVIX_GAME_CONTROL_SECOND_ATTACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_DUAL_MOTION |
		XAVIX_GAME_CONTROL_FEATURE_WII_REMOTE),
	PROFILE(DRGQST_ROM_BAN_DBZ,
		XAVIX_GAME_CONTROL_ATTACK, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_DEFLECT, XAVIX_GAME_CONTROL_TWO_HAND_ATTACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_DUAL_MOTION |
		XAVIX_GAME_CONTROL_FEATURE_WII_REMOTE),
	PROFILE(DRGQST_ROM_EPO_HAMD,
		XAVIX_GAME_CONTROL_LEFT_PAD, XAVIX_GAME_CONTROL_RIGHT_PAD,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_CONFIRM, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_POINTER),
	PROFILE(DRGQST_ROM_TVPC_DOR,
		XAVIX_GAME_CONTROL_CONFIRM, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_POINTER |
		XAVIX_GAME_CONTROL_FEATURE_KEYBOARD),
	PROFILE(DRGQST_ROM_TVPC_HAM,
		XAVIX_GAME_CONTROL_CONFIRM, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_POINTER |
		XAVIX_GAME_CONTROL_FEATURE_KEYBOARD),
	PROFILE(DRGQST_ROM_TVPC_HK,
		XAVIX_GAME_CONTROL_CONFIRM, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_POINTER |
		XAVIX_GAME_CONTROL_FEATURE_KEYBOARD),
	PROFILE(DRGQST_ROM_TAK_CHQ,
		XAVIX_GAME_CONTROL_ACCELERATE, XAVIX_GAME_CONTROL_BRAKE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_REAR_COMMAND,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING),
	PROFILE(DRGQST_ROM_EPO_EBOX,
		XAVIX_GAME_CONTROL_LEFT_PUNCH, XAVIX_GAME_CONTROL_RIGHT_PUNCH,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_MOTION),
	PROFILE(DRGQST_ROM_EPO_ES2J,
		XAVIX_GAME_CONTROL_CONFIRM, XAVIX_GAME_CONTROL_BACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_CARD_ACTION,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, 0),
	PROFILE(DRGQST_ROM_EPO_HAMC,
		XAVIX_GAME_CONTROL_CONFIRM, XAVIX_GAME_CONTROL_BACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_MOTION),
	PROFILE(DRGQST_ROM_TOM_DPGM,
		XAVIX_GAME_CONTROL_CONFIRM, XAVIX_GAME_CONTROL_BACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_POINTER),
	PROFILE(DRGQST_ROM_EPO_MINI,
		XAVIX_GAME_CONTROL_CONFIRM, XAVIX_GAME_CONTROL_BACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_MOTION),
	PROFILE(DRGQST_ROM_EPO_DTCJ,
		XAVIX_GAME_CONTROL_TILT_FORWARD,
		XAVIX_GAME_CONTROL_TILT_BACKWARD,
		XAVIX_GAME_CONTROL_TILT_LEFT,
		XAVIX_GAME_CONTROL_TAKECOPTER_BOOST,
		XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_TILT_RIGHT,
		XAVIX_GAME_CONTROL_TILT_CENTER,
		XAVIX_GAME_CONTROL_FEATURE_MOTION |
		XAVIX_GAME_CONTROL_FEATURE_WII_REMOTE),
	PROFILE(DRGQST_ROM_RAD_MTRK,
		XAVIX_GAME_CONTROL_ACCELERATE, XAVIX_GAME_CONTROL_BRAKE,
		XAVIX_GAME_CONTROL_REVERSE, XAVIX_GAME_CONTROL_NITRO,
		XAVIX_GAME_CONTROL_HORN_SELECT, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING),
	PROFILE(DRGQST_ROM_RAD_SNOW,
		XAVIX_GAME_CONTROL_FORWARD_GO, XAVIX_GAME_CONTROL_SELECT,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING),
	PROFILE(DRGQST_ROM_RAD_SSX,
		XAVIX_GAME_CONTROL_FORWARD_GO, XAVIX_GAME_CONTROL_SELECT,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING),
	PROFILE(DRGQST_ROM_RAD_SBW,
		XAVIX_GAME_CONTROL_FORWARD_GO, XAVIX_GAME_CONTROL_SELECT,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING),
	PROFILE(DRGQST_ROM_TAK_GIN,
		XAVIX_GAME_CONTROL_FORWARD_GO, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING),
	PROFILE(DRGQST_ROM_TCARNAVI,
		XAVIX_GAME_CONTROL_ACCELERATE, XAVIX_GAME_CONTROL_BRAKE,
		XAVIX_GAME_CONTROL_REVERSE, XAVIX_GAME_CONTROL_SIREN_TRANSFORM,
		XAVIX_GAME_CONTROL_IGNITION_KEY, XAVIX_GAME_CONTROL_HORN_SELECT,
		XAVIX_GAME_CONTROL_LIGHTS, XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING),
	PROFILE(DRGQST_ROM_TOMTHR,
		XAVIX_GAME_CONTROL_HORN_SELECT, XAVIX_GAME_CONTROL_IGNITION_KEY,
		XAVIX_GAME_CONTROL_WIPERS, XAVIX_GAME_CONTROL_MAP,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_MICROPHONE,
		XAVIX_GAME_CONTROL_LIGHTS, XAVIX_GAME_CONTROL_FEATURE_ANALOG_STEERING),
	PROFILE(DRGQST_ROM_EPO_CROK,
		XAVIX_GAME_CONTROL_ATTACK, XAVIX_GAME_CONTROL_SECOND_ATTACK,
		XAVIX_GAME_CONTROL_RED_BUTTON, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_DUAL_MOTION),
	PROFILE(DRGQST_ROM_TAK_ZUBA,
		XAVIX_GAME_CONTROL_BLUE_SWORD, XAVIX_GAME_CONTROL_RED_SWORD,
		XAVIX_GAME_CONTROL_BLUE_TRIGGER, XAVIX_GAME_CONTROL_RED_TRIGGER,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_DUAL_MOTION),
	PROFILE(DRGQST_ROM_DUELMAST,
		XAVIX_GAME_CONTROL_CONFIRM, XAVIX_GAME_CONTROL_BACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_SPECIAL,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_POINTER),
	PROFILE(DRGQST_ROM_EPO_GOLF,
		XAVIX_GAME_CONTROL_CADDY_CONFIRM, XAVIX_GAME_CONTROL_MODEL_BACK,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_NONE,
		XAVIX_GAME_CONTROL_NONE, XAVIX_GAME_CONTROL_FEATURE_MOTION)
};

const xavix_game_control_profile *xavix_game_control_profile_for_kind(
	enum drgqst_rom_kind kind)
{
	size_t index;
	for (index = 0; index < sizeof(GAME_CONTROL_PROFILES) /
		sizeof(GAME_CONTROL_PROFILES[0]); ++index)
	{
		if (GAME_CONTROL_PROFILES[index].kind == kind)
			return &GAME_CONTROL_PROFILES[index];
	}
	return NULL;
}

int xavix_game_control_action_visible(const xavix_game_control_profile *profile,
	enum xavix_controller_action action)
{
	return profile && action >= 0 && action < XAVIX_CONTROLLER_ACTION_COUNT &&
		profile->actions[action] != XAVIX_GAME_CONTROL_NONE;
}

size_t xavix_game_control_profile_count(void)
{
	return sizeof(GAME_CONTROL_PROFILES) / sizeof(GAME_CONTROL_PROFILES[0]);
}

const xavix_game_control_profile *xavix_game_control_profile_at(size_t index)
{
	return index < xavix_game_control_profile_count() ?
		&GAME_CONTROL_PROFILES[index] : NULL;
}

enum
{
	CONTROL_LANGUAGE_ZH_TW,
	CONTROL_LANGUAGE_ENGLISH,
	CONTROL_LANGUAGE_JAPANESE,
	CONTROL_LANGUAGE_FRENCH,
	CONTROL_LANGUAGE_COUNT
};

static const wchar_t *const GAME_CONTROL_LABELS
	[XAVIX_GAME_CONTROL_COUNT][CONTROL_LANGUAGE_COUNT] =
{
	{ L"", L"", L"", L"" },
	{ L"攻擊", L"Attack", L"攻撃", L"Attaque" },
	{ L"第二攻擊", L"Second attack", L"第2攻撃", L"Seconde attaque" },
	{ L"防禦", L"Defense", L"防御", L"Défense" },
	{ L"必殺技", L"Special move", L"必殺技", L"Technique spéciale" },
	{ L"魔法", L"Magic", L"魔法", L"Magie" },
	{ L"確認", L"Confirm", L"決定", L"Confirmer" },
	{ L"返回／取消", L"Back / cancel", L"戻る／キャンセル", L"Retour / annuler" },
	{ L"左感應點動作", L"Left sensor action", L"左センサー動作", L"Action capteur gauche" },
	{ L"右感應點動作", L"Right sensor action", L"右センサー動作", L"Action capteur droit" },
	{ L"雙感應點動作", L"Both sensor action", L"両センサー動作", L"Action des deux capteurs" },
	{ L"彈開／反擊", L"Deflect / counter", L"はじき／反撃", L"Dévier / contrer" },
	{ L"加速", L"Accelerate", L"アクセル", L"Accélérer" },
	{ L"煞車／減速", L"Brake / slow down", L"ブレーキ／減速", L"Freiner / ralentir" },
{ L"暫停", L"Pause", L"ポーズ", L"Pause" },
	{ L"後方指令", L"Rear command", L"後方コマンド", L"Commande arrière" },
	{ L"喇叭／選擇", L"Horn / select", L"ホーン／選択", L"Klaxon / sélectionner" },
	{ L"氮氣加速", L"Nitro", L"ニトロ", L"Nitro" },
{ L"倒車／後退", L"Reverse", L"バック／後退", L"Marche arrière" },
{ L"點火／鑰匙", L"Ignition / key", L"点火／キー", L"Contact / clé" },
{ L"警笛／變形", L"Siren / transform", L"サイレン／変形", L"Sirène / transformation" },
	{ L"車燈", L"Lights", L"ライト", L"Feux" },
{ L"雨刷", L"Wipers", L"ワイパー", L"Essuie-glaces" },
{ L"前進／開始", L"Forward / go", L"前進／スタート", L"Avancer / démarrer" },
{ L"選擇", L"Select", L"選択", L"Sélectionner" },
{ L"地圖", L"Map", L"マップ", L"Carte" },
{ L"麥克風", L"Microphone", L"マイク", L"Microphone" },
	{ L"玩家 1 動作", L"Player 1 action", L"プレイヤー1動作", L"Action joueur 1" },
	{ L"玩家 2 動作", L"Player 2 action", L"プレイヤー2動作", L"Action joueur 2" },
	{ L"左側踏墊", L"Left pad", L"左パッド", L"Tapis gauche" },
	{ L"右側踏墊", L"Right pad", L"右パッド", L"Tapis droit" },
	{ L"左拳", L"Left punch", L"左パンチ", L"Poing gauche" },
	{ L"右拳", L"Right punch", L"右パンチ", L"Poing droit" },
	{ L"掃卡／卡片動作", L"Card scan / action", L"カードスキャン／動作", L"Scanner / action carte" },
	{ L"火箭炮", L"Bazooka", L"バズーカ", L"Bazooka" },
	{ L"翻轉感應器", L"Reverse sensor", L"センサー反転", L"Inverser le capteur" },
	{ L"旋轉感應器", L"Spin sensor", L"センサー回転", L"Faire pivoter le capteur" },
	{ L"劍擊", L"Sword attack", L"剣攻撃", L"Attaque à l'épée" },
	{ L"光劍旋轉", L"Lightsaber spin", L"ライトセーバー回転", L"Rotation du sabre laser" },
	{ L"紅色按鈕", L"Red button", L"赤ボタン", L"Bouton rouge" },
	{ L"藍刀攻擊", L"Blue sword attack", L"青刀攻撃", L"Attaque sabre bleu" },
	{ L"紅刀攻擊", L"Red sword attack", L"赤刀攻撃", L"Attaque sabre rouge" },
	{ L"藍刀扳機", L"Blue sword trigger", L"青刀トリガー", L"Gâchette sabre bleu" },
	{ L"紅刀扳機", L"Red sword trigger", L"赤刀トリガー", L"Gâchette sabre rouge" },
	{ L"球僮／確認", L"Caddy / confirm", L"キャディ／決定", L"Caddie / confirmer" },
	{ L"球桿模型／返回", L"Club model / back", L"クラブ模型／戻る", L"Modèle club / retour" },
	{ L"合掌／結印", L"Join hands / hand sign", L"合掌／印", L"Joindre les mains / signe" },
	{ L"施放／攻擊", L"Execute / attack", L"発動／攻撃", L"Exécuter / attaquer" },
	{ L"反光點 1 攻擊", L"Reflector 1 attack", L"反射点1攻撃", L"Attaque réflecteur 1" },
	{ L"反光點 2 攻擊", L"Reflector 2 attack", L"反射点2攻撃", L"Attaque réflecteur 2" },
	{ L"雙手攻擊", L"Two-hand attack", L"両手攻撃", L"Attaque à deux mains" },
	{ L"頭部前傾／開始", L"Tilt forward / start", L"前に傾ける／スタート", L"Incliner en avant / démarrer" },
	{ L"頭部後仰", L"Tilt backward", L"後ろに傾ける", L"Incliner en arrière" },
	{ L"頭部左傾", L"Tilt left", L"左に傾ける", L"Incliner à gauche" },
	{ L"頭部右傾", L"Tilt right", L"右に傾ける", L"Incliner à droite" },
	{ L"頭部回正", L"Return upright", L"中央に戻す", L"Revenir au centre" },
	{ L"快速後仰→前傾加速", L"Back-forward boost", L"後ろ→前で加速", L"Accélération arrière-avant" }
};

const wchar_t *xavix_game_control_label_text(
	enum xavix_game_control_label label, unsigned language)
{
	if (label <= XAVIX_GAME_CONTROL_NONE ||
		label >= XAVIX_GAME_CONTROL_COUNT)
		return L"";
	if (language >= CONTROL_LANGUAGE_COUNT)
		language = CONTROL_LANGUAGE_ENGLISH;
	return GAME_CONTROL_LABELS[label][language];
}
